// Generated by unRap v1.06 by Kegetys
class CfgPatches {
	class tmr_hiteffects {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.6;
		requiredAddons[] = {"A3_Weapons_F", "A3_Characters_F", "tmr_core"};
		version = 0.1;
		author[] = {"Taosenai"};
		authorUrl = "http://www.ryanschultz.org/tmr/";
	};
};
