class CfgPt {
    AI_KNOWLEDGE_THRESHOLD = 2
    MAX_DIST_TO_COVER = 50
    MIN_HEIGHT_OBJ_TO_CONSIDER = 0.20
    CHANCE_USE_BUILDING_POS = 0.2


    DT_OUTSIDE = 3
    DT_IN_STRUCT_AM_VIS_CHANGE_POS = 3
    DT_IN_STRUCT_HIT = 3
    DT_IN_STRUCT_NOT_HIT = 3
    DT_IN_STRUCT_UNKNOWN_ENEMY = 3
    DT_IN_STRUCT_AM_VIS_MOVE = 3

    AT_OUTSIDE = 45
    AT_IN_STRUCT_AM_VIS_CHANGE_POS = 45
    AT_IN_STRUCT_HIT = 45
    AT_IN_STRUCT_NOT_HIT = 45
    AT_IN_STRUCT_AM_VIS_MOVE = 45

    AD_OUTSIDE = 250
    AD_IN_STRUCT_AM_VIS_CHANGE_POS = 50
    AD_IN_STRUCT_HIT = 50
    AD_IN_STRUCT_NOT_HIT = 50
    AD_IN_STRUCT_AM_VIS_MOVE = 50

    RT_OUTSIDE = 10
    RT_IN_STRUCT_HIT = 10
    RT_IN_STRUCT_CHANGE_POS = 10
    RT_IN_STRUCT_AM_VIS_MOVE = 10
    RT_IN_STRUCT_UNKNOWN_ENEMY = 10


}