// Generated by unRap v1.06 by Kegetys

class CfgSounds {
	class tmr_hiteffects_ringing {
		name = "tmr_hiteffects_ringing";
		sound[] = {"\tmr_hiteffects\data\ringing.ogg", "db+5", 1};
		titles[] = {};
	};
	
	class tmr_hiteffects_ringingSlight {
		name = "tmr_hiteffects_ringingSlight";
		sound[] = {"\tmr_hiteffects\data\ringingSlight.ogg", "db+2", 1};
		titles[] = {};
	};
};
